import type { Metadata } from "next";
import { Saira } from "next/font/google";
import "./styles/globals.css";
import Navbar from "@/components/layout/Navbar/Navbar";

const saira = Saira({
  variable: "--font-saira",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="es"
      suppressHydrationWarning
    >
      <body
        className={`${saira.variable} antialiased bg-grey-3 leading-relaxed text-base font-primary`}
      >
          <Navbar />
          {children}
      </body>
    </html>
  );
}
